version: '3.4'
services:
  api:
    build:
      context: posters
      dockerfile: Dockerfile
    depends_on:
      - redis
      - mongo
    command: gunicorn --config ./config/gunicorn_config.py startup:create_app()
    environment:
    - DYNACONF_CELERY_BROKER_URL="redis://redis:6379/0"
    - DYNACONF_CELERY_RESULT_BACKEND="redis://redis:6379/0"
    - DYNACONF_MONGODB_HOST="mongo"
    - DYNACONF_IMAGES_OUTPUT_PATH="/output"
    ports:
    - "8000:8000"    
    restart: always
    volumes:
    - "./output:/output"
  worker:
    build:
      context: posters
      dockerfile: Dockerfile  
    depends_on:
      - redis
      - mongo
    command: celery -A entrypoint_celery.celery worker --loglevel=info
    environment:
    - DYNACONF_CELERY_BROKER_URL="redis://redis:6379/0"
    - DYNACONF_CELERY_RESULT_BACKEND="redis://redis:6379/0"
    - DYNACONF_MONGODB_HOST="mongo"  
    - DYNACONF_IMAGES_OUTPUT_PATH="/output"  
    restart: always
    volumes:
    - "./output:/output"
  flower:
    build:
      context: posters
      dockerfile: Dockerfile    
    depends_on:
      - redis
      - mongo
    command: celery -A entrypoint_celery.celery flower --loglevel=info --port=5000
    environment:
    - DYNACONF_CELERY_BROKER_URL="redis://redis:6379/0"
    - DYNACONF_CELERY_RESULT_BACKEND="redis://redis:6379/0"
    ports:
    - "5000:5000"
  redis:
    image: redis:alpine  
    ports:
      - "6379:6379"
  mongo:
    image: mongo
    ports:
    - "27017:27017"